<?php
$this -> headMeta() -> appendHttpEquiv('Content-Type', 'text/html;charset=utf-8');
$this -> headTitle() -> setSeparator(' - ');
$this -> headTitle('Zend Backbone');
$controllername =  Zend_Controller_Front::getInstance()->getRequest()->getControllerName();
?>
<!DOCTYPE HTML>
<html>
	<head>
		<title>Zend Backbone</title>
		<!--<?php echo $this -> headLink() -> prependStylesheet($this -> baseUrl() . '/resources/css/styles.css');?>-->
		<?php echo $this -> headMeta();?>
		<?php echo $this -> headTitle();?>
	</head>

	<body>
		<?php if($controllername == 'How-it-works'): ?>
		 	<?php echo $this->partial('_partials/how-it-works-sub-nav.phtml') ?>
		 	<div id="how-it-works-container">
			<?php echo $this -> layout() -> content; ?>
		 	</div>
		<?else:?>		 
		 	<?php echo $this -> layout() -> content; ?>
		<?php endif; ?>
		 	
		 ?>
		<?php
		$this -> headScript() -> prependFile('/resources/js/lib/mustache.js', 'text/javascript');
		$this -> headScript() -> prependFile('/resources/js/lib/backbone-min.js', 'text/javascript');
		$this -> headScript() -> prependFile('/resources/js/lib/underscore-min.js', 'text/javascript');
		$this -> headScript() -> prependFile('/resources/js/lib/jquery-1.7.1.min.js', 'text/javascript');
		?>
		<?php echo $this->headScript()?>
		
	</body>
</html>