<ul>
	<li><a class='backbone-url' href="/How-it-works/index">Introduction</a></li>
	<li><a class='backbone-url' href="/How-it-works/electric-cars">Electric Cars</a></li>
	<li><a class='backbone-url' href="/How-it-works/switchable-batteries">Switchable Batteries</a></li>
	<li><a class='backbone-url' href="/How-it-works/battery-switch-stations">Battery Switch Stations</a></li>
	<li><a class='backbone-url' href="/How-it-works/charge-spots">Charge Spots</a></li>
	<li><a class='backbone-url' href="/How-it-works/better-place-oscar">Better Place Oscar</a></li>
	<li><a class='backbone-url' href="/How-it-works/customer-care">Customer Care</a></li>
	<li><a class='backbone-url' href="/How-it-works/smart-energy-management">Smart Energy Management</a></li>
</ul>
